package models

import (
	"time"

	"gorm.io/gorm"
)

type Group struct {
	ID     uint   `gorm:"primaryKey" json:"id"`
	Name   string `gorm:"size:255;not null" json:"name"`
	Status string `gorm:"size:50;default:'ACTIVE'" json:"status"`

	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
}

// TableName overrides the default table name generated by GORM
func (Group) TableName() string {
	return "groups"
}
