package models

import (
	"time"

	"gorm.io/gorm"
)

type ProcessRequest struct {
	ID                     string         `gorm:"primaryKey;column:id;type:char(36)" json:"id"`
	ProcessID              string         `gorm:"column:process_id;type:char(36)" json:"process_id"`
	UserID                 string         `gorm:"column:user_id;type:char(36)" json:"user_id"`
	ParticipantID          string         `gorm:"column:participant_id;type:char(36)" json:"participant_id"`
	Status                 string         `gorm:"column:status;size:50" json:"status"`
	Name                   string         `gorm:"column:name;size:255" json:"name"`
	CallableID             string         `gorm:"column:callable_id;type:char(36)" json:"callable_id"`
	ProcessCollaborationID string         `gorm:"column:process_collaboration_id;type:char(36)" json:"process_collaboration_id"`

	InitiatedAt time.Time      `gorm:"column:initiated_at" json:"initiated_at"`
	CompletedAt *time.Time     `gorm:"column:completed_at" json:"completed_at,omitempty"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"index;column:deleted_at" json:"-"`

	// Relations
	User *User `gorm:"foreignKey:UserID" json:"user,omitempty"`
}

// TableName overrides the default table name generated by GORM
func (ProcessRequest) TableName() string {
	return "process_requests"
}
