package models

import (
	"time"

	"gorm.io/gorm"
)

type ProcessRequestToken struct {
	ID               string `gorm:"primaryKey;column:id;type:char(36)" json:"id"`
	ProcessID        string `gorm:"column:process_id;type:char(36)" json:"process_id"`
	ProcessRequestID string `gorm:"column:process_request_id;type:char(36)" json:"process_request_id"`
	UserID           string `gorm:"column:user_id;type:char(36)" json:"user_id"`
	ElementID        string `gorm:"column:element_id;size:255" json:"element_id"`
	ElementType      string `gorm:"column:element_type;size:255" json:"element_type"`
	ElementName      string `gorm:"column:element_name;size:255" json:"element_name"`
	Status           string `gorm:"column:status;size:50;default:'ACTIVE'" json:"status"`
	IsSelfService    bool   `gorm:"column:is_self_service;default:false" json:"is_self_service"`

	DueAt       *time.Time     `gorm:"column:due_at" json:"due_at,omitempty"`
	InitiatedAt time.Time      `gorm:"column:initiated_at" json:"initiated_at"`
	CompletedAt *time.Time     `gorm:"column:completed_at" json:"completed_at,omitempty"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"index;column:deleted_at" json:"-"`

	// Relations
	User           *User           `gorm:"foreignKey:UserID" json:"user,omitempty"`
	ProcessRequest *ProcessRequest `gorm:"foreignKey:ProcessRequestID" json:"process_request,omitempty"`
}

// TableName overrides the default table name generated by GORM
func (ProcessRequestToken) TableName() string {
	return "process_request_tokens"
}
