package models

import (
	"time"

	"gorm.io/gorm"
)

type User struct {
	ID                    uint           `gorm:"primaryKey" json:"id"`
	Username              string         `gorm:"size:255;not null;unique" json:"username"`
	Email                 string         `gorm:"size:255;not null;unique" json:"email"`
	Password              string         `gorm:"size:255;not null" json:"-"`
	Firstname             string         `gorm:"size:255" json:"firstname"`
	Lastname              string         `gorm:"size:255" json:"lastname"`
	Status                string         `gorm:"size:50;default:'ACTIVE'" json:"status"`
	IsAdministrator       bool           `gorm:"default:false" json:"is_administrator"`
	Timezone              string         `gorm:"size:100;default:'UTC'" json:"timezone"`
	Language              string         `gorm:"size:50;default:'en'" json:"language"`
	Title                 string         `gorm:"size:255" json:"title"`
	ForceChangePassword   bool           `gorm:"default:false" json:"force_change_password"`
	EmailTaskNotification bool           `gorm:"default:true" json:"email_task_notification"`

	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
}

// TableName overrides the default singular table name generated by GORM
func (User) TableName() string {
	return "users"
}

// GetFullName returns the combined firstname and lastname
func (u *User) GetFullName() string {
	if u.Firstname == "" && u.Lastname == "" {
		return u.Username
	}
	return u.Firstname + " " + u.Lastname
}
